name: asroo_store
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
#? dart run build_runner build --delete-conflicting-outputs
dependencies:
  animate_do: ^3.3.4
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.2
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  flutter_zoom_drawer: ^3.2.0
  fluttertoast: ^8.2.10
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  image_picker: ^1.1.2
  package_info_plus: ^8.1.4
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.7
  share_plus: ^10.1.4
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  webview_flutter: ^4.10.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.5
  json_serializable: ^6.9.0
  very_good_analysis: ^6.0.0
flutter_launcher_icons:
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/core/
    - .env.dev
    - .env.prod
    - lang/ar.json
    - lang/en.json
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/

  fonts:
    # Arabic font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400

    # English font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
